### PR TITLE
Add physio data

### PR DESCRIPTION
**Pull request by me-pic**
Add segmented raw physio data (PPG, ECG, EDA, RESP, TTL channels):
- tsv.gz files (timeseries)
- json sidecar (column names, sampling rate, start time)

### CODE REVIEW

**Comment by me-pic** [comment]
@bpinsard I've added the top-level physio.json file

**Comment by bpinsard** [comment]
@all-contributors please add @me-pic for data preparation

**Comment by bpinsard** [comment]
@all-contributors please add @me-pic for data preparation

**Comment by bpinsard** [comment]
@all-contributors please add @me-pic for data preparation

**Pull request merged**
